# Generated by Django 5.0.1 on 2024-02-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0004_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
    ]
