# Generated by Django 5.0.1 on 2024-02-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
